version: 0.2
phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo 'install'
      - aws --version
      - cd ${CODEBUILD_SRC_DIR}/aws/cdk
      - npm ci

  pre_build:
    commands:
      - echo 'pre build'
      - export TZ="Asia/Tokyo"

      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo $IMAGE_TAG
  post_build:
    commands:
      - cd ${CODEBUILD_SRC_DIR}/aws/cdk
      - npm run deploy:apprunner-${ENV} -- -c imageTag=$IMAGE_TAG
