version: 0.2
phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo 'install'
      - aws --version

  pre_build:
    commands:
      - echo 'pre build'
      - export TZ="Asia/Tokyo"

      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo $IMAGE_TAG
      - aws ecr get-login-password | docker login --username AWS --password-stdin $CONTAINER_REPOSITORY_URI
  build:
    commands:
      - docker build --force-rm=true -t $CONTAINER_REPOSITORY_URI:latest .
      - docker tag $CONTAINER_REPOSITORY_URI:latest $CONTAINER_REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - docker push $CONTAINER_REPOSITORY_URI:latest
      - docker push $CONTAINER_REPOSITORY_URI:$IMAGE_TAG
      - echo $IMAGE_TAG > imageTag

artifacts:
  files:
    - '**/*'
